### ISSUE TITLE
Middle click pan & hold left/right click to repeat action

### ISSUE THREAD

**Issue by ForLoveOfCats** [Stenodyon/blink#1]
By moving panning to holding middle mouse button instead of holding left click, holding left and right click can be used to perform repeated placing and removing. I would like to submit a PR for this so I've opened this bug to discuss it and make sure that this is a change worth merging before I start.

**Comment by Stenodyon** [comment]
I am not a fan of middle click especially for frequently used features, changing panning to alt+left click would be perfect however.

**Comment by ForLoveOfCats** [comment]
How about shift+left mouse button?

**Comment by Stenodyon** [comment]
:+1: Works for me.

**Comment by ForLoveOfCats** [comment]
Implemented here https://github.com/Stenodyon/blink/pull/2
