### ISSUE TITLE
Paste preview is offset from mouse when copying far from the world origin

### ISSUE THREAD

**Issue by FalsePattern** [Stenodyon/blink#12]
When something is copied far from the world origin, the paste preview is not centered on the mouse. 
![image](https://user-images.githubusercontent.com/30945458/70376184-787a4a80-1906-11ea-9890-e43b346ba619.png)

**Comment by FalsePattern** [comment]
Additional information:
System: Windows 10 x64
Game version: 0.0.1-1 preview Windows x64

**Comment by Stenodyon** [comment]
Ok I was unable to reproduce initially but it seems that happens in negative coordinates (above/to the left of the world origin)

**Comment by Stenodyon** [comment]
Fixed in 0.0.1-2 (see releases page) though that version breaks saves :/
